# Generated by Django 4.0.10 on 2023-02-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='images/placeholder.jpg', upload_to='images/'),
        ),
    ]
