# Generated by Django 4.0.10 on 2023-02-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
    ]
